name: "publish"

on:
    push:
        branches:
        - main

jobs:
    publish:
        name: publish
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v3
            - name: node
              uses: actions/setup-node@v3
              with:
                  node-version: 12
            - name: publish
            - run: npm i
            - run: npm run build